### ISSUE TITLE
Errors when running clear_bin.py

### ISSUE THREAD

**Issue by rohlay** [xiaoluLucy814/graspGripper#1]
C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\Scripts\python.exe C:/Users/Usuario/Desktop/PycharmProjects/Gripper/graspGripper/clear_bin.py
pybullet build time: Jun 29 2021 00:47:49
starting thread 0
started testThreads thread 0 with threadHandle 0000000000000488
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
Version = 4.6.0 NVIDIA 462.30
Vendor = NVIDIA Corporation
Renderer = GeForce MX130/PCIe/SSE2
b3Printf: Selected demo: Physics Server
starting thread 0
started MotionThreads thread 0 with threadHandle 0000000000000ABC
MotionThreadFunc thread started
epoch, model_miou: 5 0.9954800268472342
Traceback (most recent call last):
  File "C:/Users/Usuario/Desktop/PycharmProjects/Gripper/graspGripper/clear_bin.py", line 95, in <module>
    output = model(rgb_img)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\graspGripper\train_seg_model.py", line 96, in forward
    x1 = self.inConv(x)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\graspGripper\seg_model_parts.py", line 27, in forward
    return self.double_conv(x)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "C:\Users\Usuario\Desktop\PycharmProjects\Gripper\venv\lib\site-packages\torch\nn\modules\conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
numActiveThreads = 0
stopping threads
Thread with taskId 0 with handle 0000000000000ABC exiting
Thread TERMINATED
finished
numActiveThreads = 0
btShutDownExampleBrowser stopping threads
Thread with taskId 0 with handle 0000000000000488 exiting
Thread TERMINATED

Process finished with exit code 1

What is the casue of these errors? Do you know?

Thank you in advance

**Comment by lzylucy** [comment]
RuntimeError: Input type (torch.FloatTensor) and weight type (torch.cuda.FloatTensor) should be the same
It seems like your input data is on cpu and model itself is on gpu. I think feeding the input data to gpu can solve this issue.

Try making line 93 to `rgb_img = rgb_img.reshape([1, 3, 480, 640]).to(device)`
